version: '3'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./output:/usr/src/app/output
      - ./uploads:/usr/src/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: always 